# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    match(
      type: "appstore", 
      app_identifier: "com.idealapp.githubcicdtest",
      readonly:true) 
      # 인증서 및 프로비저닝 프로파일 관리
      
      # 🔹 환경 변수 설정
      ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "30"
      ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

    build_app(
      scheme: "TnearCICDTest",
      derived_data_path: "build/DerivedData") # Xcode 프로젝트 빌드
    upload_to_testflight # TestFlight 업로드
  end

  desc "Build and upload to Firebase"
  lane :firebase do
    match(type: "development", readonly: true) # 인증서 관리

    # 🔹 환경 변수 설정
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "30"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

    build_app(scheme: "TnearCICDTest") # Xcode 빌드
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: "briannoh@tnear.com",
      release_notes: "CI/CD 자동 배포",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
