name: iOS CI/CD

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 커밋을 가져옴

      # - name: Set Xcode version
      #   run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Check Xcode version (디버깅용)
        run: xcodebuild -version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # ✅ Ruby 3.1로 변경하여 호환성 개선
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3  # ✅ 패키지 설치 최적화
          gem install json rexml logger abbrev  # ✅ 누락된 gem 설치

      - name: Install Fastlane
        run: gem install fastlane -v 2.227.0  # ✅ Fastlane 최신 버전 설치

      - name: Decode App Store API Key
        run: echo "$APP_STORE_API_KEY_CONTENT" | base64 --decode > ./AuthKey.p8
        env:
          APP_STORE_API_KEY_CONTENT: ${{ secrets.APP_STORE_API_KEY_CONTENT }}

      - name: Set up Match and Authenticate with App Store
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle exec fastlane match appstore --readonly false

      - name: Build and upload to TestFlight
        run: bundle exec fastlane beta
        env:
          APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
          APP_STORE_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_API_KEY_ISSUER_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Build and upload to Firebase
        run: bundle exec fastlane firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

      - name: Debug with SSH (옵션)
        if: failure()
        uses: mxschmitt/action-tmate@v3
